import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from email.mime.application import MIMEApplication
from typing import List

# Email configuration from environment variables
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_PORT = int(os.environ.get("SMTP_PORT", "587"))
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASSWORD = os.environ.get("SMTP_PASSWORD", "")
FROM_EMAIL = os.environ.get("FROM_EMAIL", SMTP_USER)
FROM_NAME = os.environ.get("FROM_NAME", "AI Meeting Minutes")

def send_meeting_minutes(to_emails: List[str], meeting_title: str, meeting_date: str, 
                        summary: str, pdf_path: str = None) -> bool:
    """
    Send meeting minutes via email
    
    Args:
        to_emails: List of recipient email addresses
        meeting_title: Title of the meeting
        meeting_date: Date of the meeting
        summary: Meeting summary text
        pdf_path: Optional path to PDF attachment
        
    Returns:
        bool: True if email sent successfully, False otherwise
    """
    
    if not SMTP_USER or not SMTP_PASSWORD:
        logging.error("SMTP credentials not configured. Please set SMTP_USER and SMTP_PASSWORD.")
        raise Exception("Email service not configured. Please contact administrator.")
    
    if not to_emails:
        logging.error("No recipient emails provided")
        raise Exception("No recipient email addresses provided")
    
    try:
        # Create message
        msg = MIMEMultipart('alternative')
        msg['Subject'] = f"Meeting Minutes: {meeting_title}"
        msg['From'] = f"{FROM_NAME} <{FROM_EMAIL}>"
        msg['To'] = ", ".join(to_emails)
        
        # Create email body
        text_body = f"""
Meeting Minutes: {meeting_title}
Date: {meeting_date}

{summary}

---
This email was automatically generated by the AI Meeting Minutes system.
        """
        
        html_body = f"""
        <html>
            <head>
                <style>
                    body {{ font-family: Arial, sans-serif; line-height: 1.6; color: #333; }}
                    .header {{ background-color: #007bff; color: white; padding: 20px; text-align: center; }}
                    .content {{ padding: 20px; }}
                    .summary {{ background-color: #f8f9fa; padding: 15px; border-left: 4px solid #007bff; margin: 20px 0; }}
                    .footer {{ text-align: center; color: #666; font-size: 12px; padding: 20px; border-top: 1px solid #ddd; }}
                    h1 {{ margin: 0; }}
                    h2 {{ color: #007bff; }}
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>🎤 Meeting Minutes</h1>
                </div>
                <div class="content">
                    <h2>{meeting_title}</h2>
                    <p><strong>Date:</strong> {meeting_date}</p>
                    
                    <div class="summary">
                        <h3>Summary</h3>
                        <pre style="white-space: pre-wrap; font-family: Arial, sans-serif;">{summary}</pre>
                    </div>
                </div>
                <div class="footer">
                    <p>This email was automatically generated by the AI Meeting Minutes system.</p>
                </div>
            </body>
        </html>
        """
        
        # Attach text and HTML parts
        part1 = MIMEText(text_body, 'plain')
        part2 = MIMEText(html_body, 'html')
        msg.attach(part1)
        msg.attach(part2)
        
        # Attach PDF if provided
        if pdf_path and os.path.exists(pdf_path):
            with open(pdf_path, 'rb') as pdf_file:
                pdf_attachment = MIMEApplication(pdf_file.read(), _subtype='pdf')
                pdf_attachment.add_header('Content-Disposition', 'attachment', 
                                        filename=f'{meeting_title}_minutes.pdf')
                msg.attach(pdf_attachment)
        
        # Send email
        logging.info(f"Connecting to SMTP server {SMTP_HOST}:{SMTP_PORT}")
        with smtplib.SMTP(SMTP_HOST, SMTP_PORT) as server:
            server.starttls()
            server.login(SMTP_USER, SMTP_PASSWORD)
            server.send_message(msg)
        
        logging.info(f"Email sent successfully to {len(to_emails)} recipient(s)")
        return True
        
    except smtplib.SMTPAuthenticationError:
        logging.error("SMTP authentication failed. Please check your email credentials.")
        raise Exception("Email authentication failed. Please check your email settings.")
    except smtplib.SMTPException as e:
        logging.error(f"SMTP error: {str(e)}")
        raise Exception(f"Failed to send email: {str(e)}")
    except Exception as e:
        logging.error(f"Error sending email: {str(e)}")
        raise Exception(f"Failed to send email: {str(e)}")


def parse_participant_emails(participants_text: str) -> List[str]:
    """
    Parse and extract email addresses from participants text
    
    Args:
        participants_text: Comma-separated list of names and/or emails
        
    Returns:
        List of valid email addresses
    """
    import re
    
    if not participants_text:
        return []
    
    # Email regex pattern
    email_pattern = r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b'
    
    # Extract all email addresses
    emails = re.findall(email_pattern, participants_text)
    
    # Remove duplicates while preserving order
    seen = set()
    unique_emails = []
    for email in emails:
        email_lower = email.lower()
        if email_lower not in seen:
            seen.add(email_lower)
            unique_emails.append(email)
    
    return unique_emails
